### ISSUE TITLE
Binary you added not win32

### ISSUE THREAD

**Issue by DimastyK** [kajott/TrackMeister#1]

**Comment by kajott** [comment]
It's a plain Win32 application, not UWP or anything else.

Maybe you confused the platform (which is Win32) with the architecture (which is x86_64)? I'll try to be more diligent in the future and include the architecture in the release file name as well.

**Comment by DimastyK** [comment]
> It's a plain Win32 application, not UWP or anything else.
> 
> Maybe you confused the platform (which is Win32) with the architecture (which is x86_64)? I'll try to be more diligent in the future and include the architecture in the release file name as well.

app doesn't run on windows7 32bit - "Bad descriptor"

**Comment by kajott** [comment]
Yes, it doesn't run on 32-bit x86 Windows; sorry for that. I have to admit that I never tried to build it for 32-bit x86, but I don't know why it shouldn't. I may give it a try later.

**Comment by kajott** [comment]
Here's a 32-bit build:
[TrackMeister-v1.0.0-win32-x86.zip](https://github.com/kajott/TrackMeister/files/13740743/TrackMeister-v1.0.0-win32-x86.zip)

Please keep two things in mind:
- It's untested. (I built it in a Remote Desktop session without sound, so I couldn't test it fully.)
- It's built against the current Windows SDK, which targets Windows 10 version 1903 or later, so it might not work on operating systems that are almost four years out of support!

**Comment by DimastyK** [comment]
> Here's a 32-bit build: [TrackMeister-v1.0.0-win32-x86.zip](https://github.com/kajott/TrackMeister/files/13740743/TrackMeister-v1.0.0-win32-x86.zip)
> 
> Please keep two things in mind:
> 
> * It's untested. (I built it in a Remote Desktop session without sound, so I couldn't test it fully.)
> * It's built against the current Windows SDK, which targets Windows 10 version 1903 or later, so it might not work on operating systems that are almost four years out of support!

Now "Could not create GL Context". Boring, huh?

**Comment by kajott** [comment]
Graphics card or drivers too old? OpenGL 3.3 is required.

**Comment by DimastyK** [comment]
> Graphics card or drivers too old? OpenGL 3.3 is required.

3.0, there is no new version for this video card. Anyway, thanks for your patience and for doing that.
