### ISSUE TITLE
Feature Request: Volume slider

### ISSUE THREAD

**Issue by franzmondlichtmann** [kajott/TrackMeister#5]
Sets the volume with a slider.
Keybinding for the slider with + / -
The use case is that I want to have other videos on the background (multiple audio streams at once).
And I don't want the tracker music to be too loud.

**Comment by kajott** [comment]
Implemented in da296dd.
There has already been an option like this, in the form of the `gain` parameter in the INI file, but since that can't be adjusted at runtime, an additional volume control stage has been added.
