### ISSUE TITLE
Cannot jump backwards across a +++ pattern

### ISSUE THREAD

**Issue by sagamusix** [kajott/TrackMeister#7]
When using the left arrow key to jump back by one order, TrackMeister gets stuck as soon as it encounters a "+++" (skip) pattern. IIRC the order list value (`get_order_pattern`) of that pattern should be 65534. When such an order is encountered, the previous order should be tried instead, until an order item < 65534 is found.

**Comment by manxorist** [comment]
We should maybe expose some kind of libopenmpt API for that, at least for determining what any such magic numbers actually are.

**Comment by kajott** [comment]
Can you provide a (lint to) an example module where this happens, so I can test a fix?

**Comment by kajott** [comment]
Fixed in ad6ef79.

**Comment by sagamusix** [comment]
https://bugs.openmpt.org/view.php?id=1766
